In [1]:
import pandas as pd


In [2]:
diabetes_data= pd.read_csv('C:/Users/jangd/OneDrive/바탕 화면/python/ml/data_sets/diabetes.csv')

# 0값을 검사할 피처명 리스트 객체 설정
zero_features = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']

# 전체 데이터 건수
total_count = diabetes_data['Glucose'].count()



In [3]:
total_count

768

In [4]:
pd.isnull(diabetes_data['Glucose']).sum() # 결측값 없는 거 확인


0

In [5]:
# 피처별로 반복하면서 데이터 값이 0인 데이터 건수 추출하고, 퍼센트 계산
import numpy as np
for feature in zero_features:
    zero_count =diabetes_data[diabetes_data[feature] == 0][feature].count()
    percent=100* (zero_count/total_count)
    print(f'{feature} 0 건수는 {zero_count} , 퍼센트는 {np.round(percent,2)} ')



Glucose 0 건수는 5 , 퍼센트는 0.65 
BloodPressure 0 건수는 35 , 퍼센트는 4.56 
SkinThickness 0 건수는 227 , 퍼센트는 29.56 
Insulin 0 건수는 374 , 퍼센트는 48.7 
BMI 0 건수는 11 , 퍼센트는 1.43 


In [6]:
# zero_feature 리스트 내부에 저장된 개별 피처들에 대해서 0값을 평균 값으로 대체
diabetes_data[zero_features]=diabetes_data[zero_features].replace(0,diabetes_data[zero_features].mean())

In [7]:
diabetes_data

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0              6    148.0           72.0      35.000000   79.799479  33.6   
1              1     85.0           66.0      29.000000   79.799479  26.6   
2              8    183.0           64.0      20.536458   79.799479  23.3   
3              1     89.0           66.0      23.000000   94.000000  28.1   
4              0    137.0           40.0      35.000000  168.000000  43.1   
..           ...      ...            ...            ...         ...   ...   
763           10    101.0           76.0      48.000000  180.000000  32.9   
764            2    122.0           70.0      27.000000   79.799479  36.8   
765            5    121.0           72.0      23.000000  112.000000  26.2   
766            1    126.0           60.0      20.536458   79.799479  30.1   
767            1     93.0           70.0      31.000000   79.799479  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [8]:
X=diabetes_data.iloc[:,:-1] # Outcome열 제거
X


Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0              6    148.0           72.0      35.000000   79.799479  33.6   
1              1     85.0           66.0      29.000000   79.799479  26.6   
2              8    183.0           64.0      20.536458   79.799479  23.3   
3              1     89.0           66.0      23.000000   94.000000  28.1   
4              0    137.0           40.0      35.000000  168.000000  43.1   
..           ...      ...            ...            ...         ...   ...   
763           10    101.0           76.0      48.000000  180.000000  32.9   
764            2    122.0           70.0      27.000000   79.799479  36.8   
765            5    121.0           72.0      23.000000  112.000000  26.2   
766            1    126.0           60.0      20.536458   79.799479  30.1   
767            1     93.0           70.0      31.000000   79.799479  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [9]:
y=diabetes_data.iloc[:,-1] #outcome열 뽑아오기
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [10]:
from sklearn.preprocessing import StandardScaler
# StandardScaler 클래스를 이용해 피처 데이터 세트에 일괄적으로 스케일링 적용
scaler=StandardScaler()


In [11]:
X_scaled= scaler.fit_transform(X) # fit하고 transform시켜주는 함수실행

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=156,stratify=y)

In [13]:
# 로지스틱 회귀로 학습,예측 및 평가 수행
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
lr_clf.fit(X_train,y_train)

LogisticRegression()

In [14]:
pred= lr_clf.predict(X_test)
pred_proba=lr_clf.predict_proba(X_test)[:,1]

In [15]:
import sys 
sys.path.append('C:/Users/jangd/OneDrive/바탕 화면/python/ml/module')
import f1_score_roc_auc as fra

In [16]:
fra.get_clf_eval(y_test,pred,pred_proba)

오차 행렬
[[90 10]
 [21 33]]
정확도: 0.7987, 정밀도: 0.7674, 재현율 :0.6111 ,F1 : 0.6804 , ROC AUC 값 : 0.8433


In [17]:
import sys 
sys.path.append('C:/Users/jangd/OneDrive/바탕 화면/python/ml/module')
import threshold

In [21]:
thresholds = [0.3,0.33,0.36,0.39,0.42,0.45,0.48,0.50]
pred_proba = lr_clf.predict_proba(X_test)
pred_proba[:,1].reshape(-1,1) # 1열로 만들기

array([[0.03561423],
       [0.20068404],
       [0.157666  ],
       [0.56657604],
       [0.41439664],
       [0.75446829],
       [0.83917261],
       [0.15064834],
       [0.19288548],
       [0.10662769],
       [0.66807128],
       [0.39434784],
       [0.04656127],
       [0.39070237],
       [0.26363069],
       [0.09221068],
       [0.79317522],
       [0.08837243],
       [0.5844643 ],
       [0.8036486 ],
       [0.41610897],
       [0.34759055],
       [0.06374481],
       [0.31740729],
       [0.29788187],
       [0.10409624],
       [0.92102879],
       [0.74917785],
       [0.17258479],
       [0.88834749],
       [0.22884491],
       [0.23579979],
       [0.11190966],
       [0.15169081],
       [0.10217543],
       [0.74205389],
       [0.22076285],
       [0.20662792],
       [0.85291458],
       [0.6633152 ],
       [0.4099781 ],
       [0.23486812],
       [0.7026767 ],
       [0.12921675],
       [0.34381359],
       [0.0147951 ],
       [0.46453351],
       [0.087

In [19]:
threshold.get_eval_by_threshold(y_test,pred_proba[:,1].reshape(-1,1),thresholds)

임곗값: 0.3
오차 행렬
[[67 33]
 [11 43]]
정확도: 0.7143, 정밀도: 0.5658, 재현율 :0.7963 ,F1 : 0.6615 , ROC AUC 값 : 0.8433
임곗값: 0.33
오차 행렬
[[72 28]
 [12 42]]
정확도: 0.7403, 정밀도: 0.6000, 재현율 :0.7778 ,F1 : 0.6774 , ROC AUC 값 : 0.8433
임곗값: 0.36
오차 행렬
[[76 24]
 [15 39]]
정확도: 0.7468, 정밀도: 0.6190, 재현율 :0.7222 ,F1 : 0.6667 , ROC AUC 값 : 0.8433
임곗값: 0.39
오차 행렬
[[78 22]
 [16 38]]
정확도: 0.7532, 정밀도: 0.6333, 재현율 :0.7037 ,F1 : 0.6667 , ROC AUC 값 : 0.8433
임곗값: 0.42
오차 행렬
[[84 16]
 [18 36]]
정확도: 0.7792, 정밀도: 0.6923, 재현율 :0.6667 ,F1 : 0.6792 , ROC AUC 값 : 0.8433
임곗값: 0.45
오차 행렬
[[85 15]
 [18 36]]
정확도: 0.7857, 정밀도: 0.7059, 재현율 :0.6667 ,F1 : 0.6857 , ROC AUC 값 : 0.8433
임곗값: 0.48
오차 행렬
[[88 12]
 [19 35]]
정확도: 0.7987, 정밀도: 0.7447, 재현율 :0.6481 ,F1 : 0.6931 , ROC AUC 값 : 0.8433
임곗값: 0.5
오차 행렬
[[90 10]
 [21 33]]
정확도: 0.7987, 정밀도: 0.7674, 재현율 :0.6111 ,F1 : 0.6804 , ROC AUC 값 : 0.8433


In [26]:
from sklearn.preprocessing  import Binarizer
# 임곗값을 0.48로 설정한 Binarizer 생성
binarizer= Binarizer(threshold=0.48)


In [29]:
# 위에서 구한 lr_clf 의 predict_proba() 예측 확률 array에서 1에 해당하는 컬럼값을 Binarizer변환.

pred_th_048 = binarizer.fit_transform(pred_proba[:,1].reshape(-1,1))
pred_th_048

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],

In [30]:
import sys 
sys.path.append('C:/Users/jangd/OneDrive/바탕 화면/python/ml/module')
import f1_score_roc_auc as fsr

In [31]:
fsr.get_clf_eval(y_test,pred_th_048,pred_proba[:,1])

오차 행렬
[[88 12]
 [19 35]]
정확도: 0.7987, 정밀도: 0.7447, 재현율 :0.6481 ,F1 : 0.6931 , ROC AUC 값 : 0.8433
